# Generated by Django 5.0.3 on 2025-05-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_message_delete_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='backgrounds/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
